# -*- coding: utf-8 -*-
"""Duplicates_in_array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Ccj1xzZsLDzdpRuPL03Zm5O9J8FfC6i
"""

#### Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.

##############################################################################################################################################
###Example 1:

###Input: nums - [1,2,3,1)
###Output: true
###############################################################################################################################################
###Example 2:

###Input: nums - [1,2,3,4) Output: falseimport array as arr
###############################################################################################################################################
def duplicates(nums):
  if n != len(set(nums)):
    return True
  else:
    return False
n = int(input("ENTER NUMBER OF ELEMENTS TO BE IN ARRAY:"))
nums = arr.array('i', [])
for i in range(0, n):
  nums.append(int(input()))

result = duplicates(nums)
result

